events {}

http {
  server {
    listen 80;

    location /auth/ {
      rewrite ^/auth/(.*)$ /$1 break;
      proxy_pass http://auth-service:3000;
    }

    location /products/ {
      rewrite ^/products/(.*)$ /$1 break;
      proxy_pass http://products-service:3001;
    }

    location /orders/ {
      rewrite ^/orders/(.*)$ /$1 break;
      proxy_pass http://orders-service:3002;
    }
  }
}
